//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicDate.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MedicDate.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Icono (28x28) para el botón Guardar. Fondo esperado: claro (texto/icono en negro).
        /// </summary>
        internal static global::System.Drawing.Bitmap guardar_black {
            get {
                object obj = ResourceManager.GetObject("guardar_black", resourceCulture);
                return ((global::System.Drawing.Bitmap)(obj));
            }
        }

        internal static global::System.Drawing.Bitmap cancelar_white {
            get {
                object obj = ResourceManager.GetObject("cancelar_white", resourceCulture);
                return ((global::System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Icono (28x28) para Perfil / usuario.
        /// </summary>
        internal static global::System.Drawing.Bitmap usuario_black {
            get {
                object obj = ResourceManager.GetObject("usuario_black", resourceCulture);
                return ((global::System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Icono (28x28) para Pacientes.
        /// </summary>
        internal static global::System.Drawing.Bitmap pacientes_black {
            get {
                object obj = ResourceManager.GetObject("pacientes_black", resourceCulture);
                return ((global::System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Icono (28x28) para Agenda / Agenda general.
        /// </summary>
        internal static global::System.Drawing.Bitmap agenda_black {
            get {
                object obj = ResourceManager.GetObject("agenda_black", resourceCulture);
                return ((global::System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Icono (28x28) para Citas.
        /// </summary>
        internal static global::System.Drawing.Bitmap confirmar_cita_black {
            get {
                object obj = ResourceManager.GetObject("confirmar_cita_black", resourceCulture);
                return ((global::System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Icono (28x28) para Reportes.
        /// </summary>
        internal static global::System.Drawing.Bitmap reportes_black {
            get {
                object obj = ResourceManager.GetObject("reportes_black", resourceCulture);
                return ((global::System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Icono (28x28) para Especialidades.
        /// </summary>
        internal static global::System.Drawing.Bitmap especialidades_black {
            get {
                object obj = ResourceManager.GetObject("especialidades_black", resourceCulture);
                return ((global::System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Icono (28x28) para Horarios.
        /// </summary>
        internal static global::System.Drawing.Bitmap horarios_black {
            get {
                object obj = ResourceManager.GetObject("horarios_black", resourceCulture);
                return ((global::System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Icono (28x28) para Asistentes.
        /// </summary>
        internal static global::System.Drawing.Bitmap asistentes_black {
            get {
                object obj = ResourceManager.GetObject("asistentes_black", resourceCulture);
                return ((global::System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Icono (28x28) para Doctores.
        /// </summary>
        internal static global::System.Drawing.Bitmap doctores_black {
            get {
                object obj = ResourceManager.GetObject("doctores_black", resourceCulture);
                return ((global::System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Icono (28x28) para Cerrar sesión. Fondo rojo (#B00B0B): icono en blanco.
        /// </summary>
        internal static global::System.Drawing.Bitmap cerrar_sesion_white {
            get {
                object obj = ResourceManager.GetObject("cerrar_sesion_white", resourceCulture);
                return ((global::System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Icono (28x28) para Nuevo/Agregar.
        /// </summary>
        internal static global::System.Drawing.Bitmap nuevo_black {
            get {
                object obj = ResourceManager.GetObject("nuevo_black", resourceCulture);
                return ((global::System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Icono (28x28) para Editar.
        /// </summary>
        internal static global::System.Drawing.Bitmap editar_black {
            get {
                object obj = ResourceManager.GetObject("editar_black", resourceCulture);
                return ((global::System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Icono (28x28) para Eliminar. Fondo rojo: icono en blanco.
        /// </summary>
        internal static global::System.Drawing.Bitmap eliminar_white {
            get {
                object obj = ResourceManager.GetObject("eliminar_white", resourceCulture);
                return ((global::System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Icono (28x28) para Desactivar. Fondo rojo: icono en blanco.
        /// </summary>
        internal static global::System.Drawing.Bitmap desactivar_white {
            get {
                object obj = ResourceManager.GetObject("desactivar_white", resourceCulture);
                return ((global::System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Icono (28x28) para Ver Detalle.
        /// </summary>
        internal static global::System.Drawing.Bitmap detalle_black {
            get {
                object obj = ResourceManager.GetObject("detalle_black", resourceCulture);
                return ((global::System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Icono (28x28) para navegación "Anterior".
        /// </summary>
        internal static global::System.Drawing.Bitmap anterior_black {
            get {
                object obj = ResourceManager.GetObject("anterior_black", resourceCulture);
                return ((global::System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Icono (28x28) para navegación "Siguiente".
        /// </summary>
        internal static global::System.Drawing.Bitmap siguiente_black {
            get {
                object obj = ResourceManager.GetObject("siguiente_black", resourceCulture);
                return ((global::System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Icono (28x28) para Acceder (login).
        /// </summary>
        internal static global::System.Drawing.Bitmap acceder_black {
            get {
                object obj = ResourceManager.GetObject("acceder_black", resourceCulture);
                return ((global::System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Icono (28x28) para Cancelar sobre fondo no rojo (ej. gris).
        /// </summary>
        internal static global::System.Drawing.Bitmap cancelar_black {
            get {
                object obj = ResourceManager.GetObject("cancelar_black", resourceCulture);
                return ((global::System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Icono (28x28) para Ver Historial.
        /// </summary>
        internal static global::System.Drawing.Bitmap ver_historial_black {
            get {
                object obj = ResourceManager.GetObject("ver_historial_black", resourceCulture);
                return ((global::System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Icono (28x28) para Iniciar Consulta.
        /// </summary>
        internal static global::System.Drawing.Bitmap iniciar_consulta_black {
            get {
                object obj = ResourceManager.GetObject("iniciar_consulta_black", resourceCulture);
                return ((global::System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Icono (28x28) para Finalizar Consulta.
        /// </summary>
        internal static global::System.Drawing.Bitmap finalizar_consulta_black {
            get {
                object obj = ResourceManager.GetObject("finalizar_consulta_black", resourceCulture);
                return ((global::System.Drawing.Bitmap)(obj));
            }
        }
    }
}
